changed file_exists to file to allow urls
char0n/ffmpeg-php pull request #56
Opened 2021-12-19 13:03 UTC by ToshY

Fixes #55

2021-12-19 19:36 UTC, char0n requested changes
Thanks for contributing! Please have a look at my code review comments. Also if we're introducing this feature, it would be good to add tests for it. Please use this testing file for testing: https://github.com/char0n/ffmpeg-php/blob/master/tests/data/test.mp4?raw=true. I can imagine following tests:

- testing if FFMpegProvider can handle URL
- testing if FFProbeProvider can handle URL
- testing if Movie can handle URL
- testing what happens when provided URL cannot be fetched

2021-12-19 19:36 UTC, char0n commented on src/OutputProviders/FFMpegProvider.php
> +        if (@file_get_contents($this->movieFile, false, null, 0, 1) === false) {
`0/0` as `offset/length` is supported as well. Let's use this one as it allows to process empty files as well.
```suggestion
        if (@file_get_contents($this->movieFile, false, null, 0, 0) === false) {
```

2021-12-19 19:36 UTC, char0n commented on src/OutputProviders/FFProbeProvider.php
> +        if (@file_get_contents($this->movieFile, false, null, 0, 1) === false) {
`0/0` as `offset/length` is supported as well. Let's use this one as it allows to process empty files as well.
```suggestion
        if (@file_get_contents($this->movieFile, false, null, 0, 0) === false) {
```

2021-12-19 21:20 UTC, ToshY commented
Well the CI seems to be fine with it, but I honestly don't know if it's okay like this, as I normally don't write tests. So I just tried to mimic the other tests and ended up with this. 
Let me know if there's something that needs to be changed.

2021-12-20 06:04 UTC, char0n approved these changes
The tests satisfy the requirements. Nicely done. I'll just do some minor cleanup in them before the release.

2021-12-20 06:10 UTC, merged